#compilando um package
go build github.com/goinaction/code/chapter3/wordcount

#compilando todos os package no diretorio
go build github.com/goinaction/code/chapter3/...

#compilando tudo no diretorio corrente
go build .